Repository ja-kanno4A/dinner_project, pull requests merged in 2025-01, with the labels that each got.

#23 Ziro task
  README.md
Labels: 次郎, 買い出し, さらだばー

#24 Hanako task
  README.md
Labels: 花子, カレー

#27 太郎スープ作りました #4 #19 #20 #21 #22
  README.md
Labels: 太郎, スープ
